#pragma once

namespace BULLET
{
	enum ID {»ó, ÇÏ, ÁÂ, ¿ì, ³¡};
}
namespace OBJ
{
	enum ID {OBJ_MONSTER, OBJ_PLAYER, OBJ_BULLET, OBJ_SHIELD, OBJ_MOUSE, OBJ_END};
	enum STATE {PLAYER_RUN, PLAYER_SLIDE, PLAYER_RUSH, PLAYER_JUMP, PLAYER_DOUBLEJUMP, PLAYER_PAIN, PLAYER_DIE};
}

namespace MAP {
	enum ID {MAP_BLOCK, MAP_OBSTACLE, MAP_COIN, MAP_JELLY, MAP_END};
	enum DETAILED_ID {
		BLOCK,
		OTC1, OTC2, OTC3, OTC4,
		SVCOIN, GDCOIN, BIGCOIN, 
		BASEJL, PINKJL, YELLOWJL, BIGJL };
}