#pragma once

namespace BULLET
{
	enum ID {»ó, ÇÏ, ÁÂ, ¿ì, ³¡};
}
namespace OBJ
{
	enum ID {OBJ_PLAYER, OBJ_PET, OBJ_MOUSE, OBJ_END};
	enum PLAYER {PLAYER_RUN, PLAYER_SLIDE, PLAYER_RUSH, PLAYER_JUMP, PLAYER_DOUBLEJUMP, PLAYER_PAIN, PLAYER_DIE};
	enum PET {PET_DEFAULT, PET_MAGNET};
}

namespace MAP {
	enum ID {MAP_BLOCK, MAP_OBSTACLE, MAP_COIN, MAP_JELLY, MAP_HP, MAP_GIANT, MAP_BOOSTER, MAP_MAGNET, MAP_END};
	enum DETAILED_ID {
		BLOCK,
		OTC1, OTC2, OTC3, OTC4,
		SVCOIN, GDCOIN, BIGCOIN, 
		BASEJL, PINKJL, YELLOWJL, BIGJL, 
		SMALLHP, BIGHP,
		GIANT,
		BOOSTER,
		MAGNET
	};
}